### ISSUE TITLE
Disable only specific animation

### ISSUE THREAD

**Issue by Yimiprod** [michalsnik/aos#112]
Is it possible to disable specific animation for specific device.
As an exemple, on mobile, i need some part of the page to not have animation, but always have other parts to have one.

Maybe a data attr like `data-aos-disable="mobile"` ?

**Comment by hellokatili** [comment]
You can do it in a media query.

Example: Disable "slide left" transition
```css
@media(max-width: 767px){
    .your-selector[data-aos=slide-left] {
        -webkit-transform: translateX(0);
        transform: translateX(0);
    }
}
```
