### ISSUE TITLE
Animate off of screen on scroll

### ISSUE THREAD

**Issue by bmcpeakserenova** [michalsnik/aos#288]
Hi there,

Is it possible to have something animate off screen when a certain distance is reached? So instead of being off-screen by default and animating onto screen when reached, the reverse would occur. The element would be on-screen by default and animate off of screen once reached.

Thanks for a great plugin!

**Comment by rafayhingoro** [comment]
I am not wrong you want it to be like if once that element is animated (triggered event) so that won't reverse or hide and should be stayed ? 
then have a look at my previous response hope this may help [https://github.com/michalsnik/aos/issues/275#issuecomment-366642628](https://github.com/michalsnik/aos/issues/275#issuecomment-366642628)

**Comment by bmcpeakserenova** [comment]
Hi @rafayhingoro, no, that's not quite what I'm looking for. I would like an element to be on the page by default, but to disappear on scroll to it. So almost the same behavior as default, but instead of animating onto the screen at the set distance, it would animate off of the screen (disappear).

Thanks!

**Comment by michalsnik** [comment]
Hey @bmcpeakserenova, you can add custom animation e.g.:
```css
[data-aos="fade-out"] {
  opacity: 1;
  transition-property: opacity;
  &.aos-animate {
    opacity: 0;
  }
}
```

And add it on your element with an extra `data-aos-anchor-placement` setting, for example:
```
<div data-aos="fade-out" data-aos-anchor-placement="top-top">test</div>
```
This elemenet will fade out once it's top edge hits top of your window. If you want it to happen soone, you can use for example `bottom-center` - once bottom of element will hit center of the screen :)

I hope it's helpful. If this doesn't address you problem feel free to reopen this issue :)

**Comment by johnep1978** [comment]
Hi Michal,
Could you please tell me where I need to paste the above code? 
Thanks!

**Comment by michalsnik** [comment]
It should be placed somewhere after the AOS’ css @johnep1878 to override it

**Comment by johnep1978** [comment]
Great thank you Michal 👍

**Comment by kdssoftware** [comment]
> Hey @bmcpeakserenova, you can add custom animation e.g.:
> 
> ```css
> [data-aos="fade-out"] {
>   opacity: 1;
>   transition-property: opacity;
>   &.aos-animate {
>     opacity: 0;
>   }
> }
> ```

Thanks a lot! 
But thats SCSS.

This is the CSS version of it, for people that need it:
```css
    [data-aos="fade-out"] {
      opacity: 1;
      transition-property: opacity;
    }
    [data-aos="fade-out"].aos-animate {
      opacity: 0;
    }
```
