### ISSUE TITLE
Use media breakpoint 

### ISSUE THREAD

**Issue by Mesiek1000** [michalsnik/aos#315]
Hello!
Can I use AOS with breakpoint? I use bootstrap.

Example:
@include media-breakpoint-only(md) { data-aos="fade-up" }
@include media-breakpoint-only(lg) { data-aos="fade-down" }

**Comment by michalsnik** [comment]
Hey @Mesiek1000 You can but you'd have to create your own animation.

E.g.:
```css
@include media-breakpoint-only(md) {
  [data-aos="example-anim"] {
    transform: skewX(45deg);
    opacity: 0;
    transition-property: transform, opacity;
    &.aos-animate {
      transform: skewX(0);
      opacity: 1;
    }
  }
}

@include media-breakpoint-only(lg) {
  [data-aos="example-anim"] {
    opacity: 0;
    transition-property: opacity;
    &.aos-animate {
      opacity: 1;
    }
  }
}
```

And use it like this:
```html
<div data-aos="custom-anim"></div>
```
