### ISSUE TITLE
Mobile customization

### ISSUE THREAD

**Issue by nelcynunez** [michalsnik/aos#340]
Hello there, 

First of all, thank you for making this library available for everyone! It is very helpful, especially for starters. 

I'm using "data-aos-delay" inline because I want some elements that are in the same section to load at different speed. But for mobile–because you'd have to scroll to see these elements–it takes too long to load, so I want to change the delay value. 

I tried doing it with a condition (see below), but it's not working; I guess the delay value in the script doesn't overwrite the one inline (?).

What would be the best way to do it?

Thanks a lot! 

```
if ($(window).width() < 1025){
		    	
		    	AOS.init({
		    		duration: 1000,
		    		easing: 'ease-in-sine',
		    		once: 'true',
		    		delay: 200
		    	});
		    		
		    	}

		    else {

		    	AOS.init({
		    		duration: 1000,
		    		easing: 'ease-in-sine',
		    		once: 'true'

		    	});
		    };
```

**Comment by thetwopct** [comment]
I'm trying to do something similar, did you find a solution?

**Comment by michalsnik** [comment]
Hey, you can add custom delay if you want using CSS:
```scss
body[data-aos-delay='custom'] [data-aos],
[data-aos][data-aos][data-aos-delay='custom']{
  transition-delay: 0s;
  
  &.aos-animate {
      transition-delay: 200ms;

      @media (min-width: 1025px) {
        transition-delay: 2s;
      }
  }
}
```
and then use it by setting either global, or inline setting:
```html
<div data-aos-delay="custom">...</div>
```
```js
AOS.init({
  ...
  delay: 'custom'
});
```
