### ISSUE TITLE
Disable: mobile

### ISSUE THREAD

**Issue by simmonsr** [michalsnik/aos#372]
Can `disable: phone` or `disable: mobile` be used on a per element basis (not global)?

**Comment by simmonsr** [comment]
If not, would be nice to see `data-aos-disable` attribute option.

**Comment by Filliposniper** [comment]
Yap +1 @simmonsr i already thought if that will be possible on an element and not globally... that's a nice idea

**Comment by numnx** [comment]
I have a little workaround for you guys, you can just wrap your aos-scss (_animations.scss) or compiled css inside a Media Query which excludes mobile devices so only the class gets toggled but nothing happens. Or you can set a default  animation for mobile devices too. Hope it helps

**Comment by simmonsr** [comment]
Would just be easier to have it be an per element basis. The developer is considering it.

**Comment by natedunn** [comment]
3 years into the future, I am sad this does not exist.

**Comment by Asmitta-01** [comment]
A workaround: https://gist.github.com/prantu/9499218ddfaf00b331e7f6a7d425c791.

```css
@media screen and (max-width: 480px) {
  .disable-aos-mobile[data-aos] {
         /*CSS transitions*/
        opacity: 1 !important;
        -o-transition-property: none !important;
        -moz-transition-property: none !important;
        -ms-transition-property: none !important;
        -webkit-transition-property: none !important;
        transition-property: none !important;
        /*CSS transforms*/
        -o-transform: none !important;
        -moz-transform: none !important;
        -ms-transform: none !important;
        -webkit-transform: none !important;
        transform: none !important;
        /*CSS animations*/
        -webkit-animation: none !important;
        -moz-animation: none !important;
        -o-animation: none !important;
        -ms-animation: none !important;
        animation: none !important;
  }
}
```
