### ISSUE TITLE
Sequential animation of elements in view

### ISSUE THREAD

**Issue by fallenartist** [michalsnik/aos#452]
If some of the elements are already in view, they animate simultaneously. I'd like to make them appear one after the other. Is it possible to chain/queue elements in view in an automatic way using JS events and possibly without having to use `data-aos-id`? 

## This is:
- Question / Feature request

## Specifications

  - AOS version: 3.0.0-beta6
  - OS: macOS
  - Browser: Safari 12.0.3

## Expected Behavior
Elements in view appear in sequence.

## Actual Behavior
Elements in view appear at once.

## Possible Solution
`AOS.init({showInSequence: true});`

**Comment by PowerSlime** [comment]
Kinda "hotfix" is to generate a bit of CSS rules with transition-delay. 

Mixin, written with Sass
```Sass
@mixin aos-transition-delay($itemsCount, $step: .1s, $reset: false)
    @if ($reset)
        &:nth-child(n).aos-animate
            transition-delay: 0s

            @content

    @for $index from 0 through ($itemsCount - 1)
        &:nth-child(#{$itemsCount}#{"n -"} #{$index}).aos-animate
            transition-delay: $step * ($itemsCount - ($index + 1))

            @content

.items
  .item
    @include aos-transition-delay(3, .2s)
```

In `itemsCount` you pass count of your items in a row, `refresh` need to clean all the mess when you're work with media queries. Also, backward animation is synchronized. To prevent it - delete `.aos-animate` from mixin.

It will generate you code like this:
```CSS
.items .item:nth-child(3n - 0).aos-animate {
  transition-delay: 0.4s;
}

.items .item:nth-child(3n - 1).aos-animate {
  transition-delay: 0.2s;
}

.items .item:nth-child(3n - 2).aos-animate {
  transition-delay: 0s;
}
```
