### ISSUE TITLE
AOS Custom Delay

### ISSUE THREAD

**Issue by nixks** [michalsnik/aos#558]
Hi everyone,

I am in need of a custom delay option over the bountry of max 3000ms which is my only option at the moment.

I tried adding the following css:

```
body[data-aos-delay='8000'] [data-aos],
  [data-aos][data-aos][data-aos-delay='8000'] {
    transition-delay: 8s;
}
```
...but no luck. Animation starts at 3 seconds...

Any suggestions? 

Thanks!

**Comment by evankford** [comment]
It looks like the CSS rule from the AOS library is applying the transition-delay once the `aos-animate` class has been added, so you may need to add that to your css rule, like so: 

```css
body [data-aos-delay='8000'][data-aos].aos-animate,
[data-aos][data-aos][data-aos-delay='8000'].aos-animate {
    transition-delay: 8s;
}
```
