### ISSUE TITLE
Interaction with CSS animations results in content being hidden incorrectly

### ISSUE THREAD

**Issue by domdomegg** [michalsnik/aos#772]
## This is:
- Bug

## Specifications

- AOS version: 3.0.0-beta.6, and 2.3.4
- OS: All (tested on Linux and Android)
- Browser: All (tested on Google Chrome, Chromium and Firefox)

## Expected Behavior

When scrolling, content should appear correctly.

## Actual Behavior

(In the situtation where you have an element that shrinks e.g. with a CSS animation above the AOS controlled elements)

Animations are not triggered at the correct scroll offsets.

## Steps to Reproduce the Problem

Demo: https://codepen.io/domdomegg/pen/wvyJmjO

<details>
<summary>Code for posterity, in case CodePen link breaks</summary>

```html
<div class="spacer">
  Scroll down to see things ⬇
</div>

<div class="item shrink">↕️ I shrink after the page loads!</div>

<div class="item" data-aos="fade-up">✨ I animate on scroll! (1)</div>
<div class="item" data-aos="fade-up">✨ I animate on scroll! (2)</div>
<div class="item" data-aos="fade-up">✨ I animate on scroll! (3)</div>
<div class="item" data-aos="fade-up">✨ I animate on scroll! (4)</div>
<div class="item" data-aos="fade-up">✨ I animate on scroll! (5)</div>
<div class="item" data-aos="fade-up">✨ I animate on scroll! (6)</div>

<div class="spacer"></div>
```

```css
* {
  box-sizing: border-box;
  text-align: center;
  font-size: 24px;
}

.spacer {
  height: 50vh;
  padding: 10vh;
}

.item {
  margin: 50px auto;
  padding: 50px;
  background: #888;
  color: #FFF;
}

.shrink {
  animation: shrink 1s forwards;
  animation-delay: 1s;
  height: 100vh;
  overflow: hidden;
}

@keyframes shrink {
  from { height: 100vh; }
  to { height: 0; padding: 0; margin: 0; }
}
```

```js
AOS.init()
```
</details>

## Possible Solution

Reason: probably because AOS caches the scroll offsets at some point, and doesn't refresh when there are CSS animations above.

The workaround we're using is a bit hacky - basically we assume that any CSS animations will run in some defined period, and then call `AOS.refresh()` with setTimeout a few seconds later, something like:

```ts
AOS.init()

// Sometimes AOS will initialise before some animations that change the page height run
// This causes a bug where elements aren't triggered at the right scroll offsets, so users
// can't see the content. We force a refresh 5s after first initalising AOS so it recalculates
// these heights, to cover for this.
const t = setTimeout(() => {
  AOS.refresh()
}, 5000)
```

However, this doesn't fix every case and is quite fragile. In particular, where we have CSS transitions triggered after (e.g. by user interaction) the AOS offsets don't get updated. It'd be quite messy to call AOS everywhere we might run an animation on the page, so that's not an ideal solution.
