### ISSUE TITLE
Without Javascript

### ISSUE THREAD

**Issue by piernik** [michalsnik/aos#81]
Great library but I have one concern.
When You turn off javascript there element is not displayed. It can be problem with SEO.
I suggest setting initial CSS rules in init() not in css file.

**Comment by petzo** [comment]
Actually I was just about to post about this. I think it can be improved too.
In the mean time I ended up quickly fixing it like this:

In the html I prepend the data-aos with "nojs-". For example: 
```html
<div data-aos="animation_name">
```
becomes:
```html
<div data-aos="nojs-animation_name">
```
Then I init like this (using jQuery):
```javascript
$(function(){
    $('*[data-aos|="nojs"]').each(function(){
      var $this = $(this); 
      $this.attr('data-aos',$this.attr('data-aos').replace('nojs-',''));
    });
    AOS.init();
});
```

**Comment by piernik** [comment]
@petzo great solution - have to try it.

**Comment by lukeshiels** [comment]
Theres a better solution without JS and this is how I do it:

```css
<head>
    <noscript>
        <style type="text/css">
            [data-aos] {
                opacity: 1 !important;
                transform: translate(0) scale(1) !important;
            }
        </style>
    </noscript>
</head>
```

The noscript must be in the head (which is [explicitly allowed according to W3C](https://www.w3.org/TR/html5/scripting-1.html#the-noscript-element), because `style` tags will only work from within the head.
