### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mirismaili** [michalsnik/aos#829]
Expected `left`/`right` animations have a variant that is automatically mirrored (`left` <-> `right`) in RTL layouts. Yes! I mean `start`/`end`.

## This is:

- Feature request

## Specifications

  - AOS version: 2.3.4

## Possible Solution

```scss
[data-aos^=fade][data-aos^=fade] {
    // ...
  .aos-animate {
    // ...
  }
}
[data-aos=fade-start] {
  [dir=rtl] & {
    transform: translate3d(-100px, 0, 0) // same as `fade-right`
  }
  transform: translate3d(100px, 0, 0) // same as `fade-left`
}
[data-aos=fade-end] {
  [dir=rtl] & {
    transform: translate3d(100px, 0, 0) // same as `fade-left`
  }
  transform: translate3d(-100px, 0, 0) // same as `fade-right`
}
```
